HOSTNAME: "fuel"
DNS_DOMAIN: "domain.tld"
DNS_SEARCH: "domain.tld"
DNS_UPSTREAM: "8.8.8.8"
NTP1: "0.fuel.pool.ntp.org"
NTP2: "1.fuel.pool.ntp.org"
NTP3: "2.fuel.pool.ntp.org"
ADMIN_NETWORK:
  interface: "eth0"
  ipaddress: "10.20.0.2"
  netmask: "255.255.255.0"
  cidr: "10.20.0.0/24"
  size: "256"
  dhcp_gateway: "10.20.0.2"
  dhcp_pool_start: "10.20.0.3"
  dhcp_pool_end: "10.20.0.254"
FUEL_ACCESS:
  user: "admin"
  password: "admin"
BOOTSTRAP:
  MIRROR_DISTRO: "http://archive.ubuntu.com/ubuntu"
  MIRROR_MOS: "http://mirror.fuel-infra.org/mos-repos/ubuntu/7.0"
  HTTP_PROXY: ""
  EXTRA_APT_REPOS: ""
  flavor: "centos"
